In [1]:
import numpy as np

In [3]:
# Arithematic Operations

In [5]:
# Standardised Arithematci Operations

In [7]:
x = np.array([[1,2],[3,4]])

In [9]:
y = np.array([[5,6],[7,8]])

In [11]:
# Addition
x + y

array([[ 6,  8],
       [10, 12]])

In [13]:
# Substraction
y - x

array([[4, 4],
       [4, 4]])

In [15]:
# Multiplication
x * y

array([[ 5, 12],
       [21, 32]])

In [17]:
# Division
y / x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [19]:
# Operations between scalar and arrays

In [21]:
x * 2

array([[2, 4],
       [6, 8]])

In [23]:
2 ** x

array([[ 2,  4],
       [ 8, 16]])

In [25]:
y / 2

array([[2.5, 3. ],
       [3.5, 4. ]])

In [27]:
2 / y

array([[0.4       , 0.33333333],
       [0.28571429, 0.25      ]])

In [29]:
(y/2).dtype

dtype('float64')

In [33]:
# Error Scenario
# x = np.array([1,2,3,4]).reshape(2,2)
# z = np.array([1,2,3,4])
# print(x/z)
'''
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[31], line 4
      2 x = np.array([1,2,3,4]).reshape(2,2)
      3 z = np.array([1,2,3,4])
----> 4 print(x/z)

ValueError: operands could not be broadcast together with shapes (2,2) (4,) 
'''

'\n---------------------------------------------------------------------------\nValueError                                Traceback (most recent call last)\nCell In[31], line 4\n      2 x = np.array([1,2,3,4]).reshape(2,2)\n      3 z = np.array([1,2,3,4])\n----> 4 print(x/z)\n\nValueError: operands could not be broadcast together with shapes (2,2) (4,) \n'

In [35]:
# Reshaping the array to broadcast together with other arrays

In [53]:
# operating 2X2 with 1X2
z = np.array([[2,4]])

In [55]:
z.shape

(1, 2)

In [57]:
x/z # Dividing the x by z means diving x by zz that is constructed by repeating the row vector z to obtain array zz that has same dimension as x

array([[0.5, 0.5],
       [1.5, 1. ]])

In [59]:
zz = np.concatenate([z,z],axis=0)

In [61]:
zz

array([[2, 4],
       [2, 4]])

In [63]:
x/zz

array([[0.5, 0.5],
       [1.5, 1. ]])

In [65]:
# Operating 2X2 with 2X1

In [67]:
z = np.array([[2],[4]])

In [69]:
z

array([[2],
       [4]])

In [71]:
z.shape

(2, 1)

In [73]:
x/z

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In [75]:
zz = np.concatenate([z,z],axis=1)

In [77]:
zz

array([[2, 2],
       [4, 4]])

In [79]:
x/zz

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In [81]:
# Using in-built functions for operations

In [83]:
a = np.array([[1,2],[3,4]])

In [85]:
b = np.array([[5,6],[7,8]])

In [87]:
np.add(a,b)

array([[ 6,  8],
       [10, 12]])

In [89]:
np.multiply(a,b)

array([[ 5, 12],
       [21, 32]])

In [93]:
np.subtract(a,b)

array([[-4, -4],
       [-4, -4]])

In [95]:
np.divide(a,b)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [97]:
np.power(a,b)

array([[    1,    64],
       [ 2187, 65536]])

In [99]:
# All the above functions are examples of vectorized operations meaning operations of 2 same size and shape arrays

In [101]:
# np.vectorize functionality 

In [107]:
def heavside(x):
    return 1 if x>0 else 0

In [109]:
heavside(-1)

0

In [111]:
heavside(1.5)

1

In [115]:
x = np.linspace(-5,5,11)

In [117]:
x

array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.])

In [121]:
# heavside(x)
'''
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[119], line 1
----> 1 heavside(x)

Cell In[107], line 2, in heavside(x)
      1 def heavside(x):
----> 2     return 1 if x>0 else 0

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
'''

'\n---------------------------------------------------------------------------\nValueError                                Traceback (most recent call last)\nCell In[119], line 1\n----> 1 heavside(x)\n\nCell In[107], line 2, in heavside(x)\n      1 def heavside(x):\n----> 2     return 1 if x>0 else 0\n\nValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()\n'

In [123]:
heavside = np.vectorize(heavside)

In [125]:
heavside(x)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [129]:
# Aggregate functions

In [133]:
data = np.random.normal(size=(15,15))

In [135]:
data

array([[ 0.3080056 , -0.16322057,  1.50553065,  0.94879182,  1.24342967,
        -0.92414972, -0.27278604, -0.51778252,  0.96532089,  0.44145724,
         0.88265903, -0.26748321,  0.87049097,  1.85527735,  0.379018  ],
       [-0.85148408,  0.40199003, -1.09602854,  1.37089463, -0.83665831,
         0.45488754, -0.41944498, -0.87572678, -0.45972793, -1.21006472,
         1.02466701,  0.03293164, -0.10202966,  1.49168647,  0.2176014 ],
       [ 0.36114733,  0.81176996,  1.33035955,  0.88469694,  1.27078863,
        -0.3873838 , -1.4768714 , -0.30452382, -0.63212231, -0.66546929,
         0.28469312,  0.47599137,  1.07118284,  2.25588966,  0.30065757],
       [-0.07812408,  1.41034352,  0.27176323,  1.63551412, -0.95370939,
        -1.0538337 ,  0.86214241,  0.35407003, -0.2574466 , -0.84830878,
        -1.29287446,  0.34013209, -0.63780669,  0.06282088, -0.35188675],
       [-1.47247475,  1.57548086, -0.66634825, -0.38273497, -0.74483988,
        -0.09832813,  0.03370632, -2.14088117, 

In [137]:
np.mean(data)

0.005955295000047961

In [139]:
data.mean()

0.005955295000047961

In [141]:
data.std()

1.0097902627061535

In [143]:
data.sum()

1.3399413750107911

In [145]:
data.cumsum()

array([ 0.3080056 ,  0.14478502,  1.65031568,  2.5991075 ,  3.84253717,
        2.91838745,  2.64560141,  2.1278189 ,  3.09313978,  3.53459703,
        4.41725606,  4.14977285,  5.02026382,  6.87554117,  7.25455917,
        6.40307509,  6.80506512,  5.70903658,  7.07993121,  6.24327291,
        6.69816045,  6.27871547,  5.40298869,  4.94326076,  3.73319604,
        4.75786305,  4.79079469,  4.68876504,  6.18045151,  6.39805291,
        6.75920024,  7.5709702 ,  8.90132975,  9.78602669, 11.05681532,
       10.66943153,  9.19256013,  8.88803631,  8.255914  ,  7.59044471,
        7.87513783,  8.3511292 ,  9.42231204, 11.6782017 , 11.97885927,
       11.90073519, 13.31107872, 13.58284194, 15.21835606, 14.26464667,
       13.21081297, 14.07295538, 14.42702541, 14.16957881, 13.32127003,
       12.02839557, 12.36852766, 11.73072097, 11.79354185, 11.4416551 ,
        9.96918035, 11.54466121, 10.87831296, 10.49557799,  9.75073811,
        9.65240998,  9.6861163 ,  7.54523513,  7.98665385,  6.79

In [147]:
data.min()

-3.0353465634214154

In [149]:
data.max()

3.299052246283727

In [151]:
data.all()

True

In [153]:
data.any()

True

In [169]:
data = np.random.normal(size=(5,10,15))

In [171]:
data

array([[[-9.52242463e-01, -1.00259437e-01, -3.65462841e-01,
          1.69085225e+00, -5.01428799e-01, -6.50354520e-01,
         -7.58060058e-01,  2.20963436e+00, -3.90614820e-01,
         -1.79792730e-01, -5.23747304e-01,  4.51473791e-01,
         -1.63466047e+00, -4.79498070e-01, -1.36625196e+00],
        [ 8.39731756e-01, -1.11490449e-01,  1.24297964e+00,
         -8.63080626e-01, -9.15212755e-01,  6.45395777e-01,
          9.44488176e-01, -4.98604266e-01,  3.43400228e-01,
         -1.53329870e-01,  9.35812982e-01,  8.13129409e-01,
         -5.79041094e-01,  1.32287654e+00, -1.48044651e+00],
        [-4.51579989e-01,  7.38376289e-01, -1.23767083e+00,
         -3.83116434e-01,  2.22038994e+00,  8.43135136e-01,
          1.61624146e+00, -3.46390044e-01,  1.15508210e+00,
         -3.27180515e-01,  2.85291447e-01, -4.00811125e-01,
          1.27349741e-01, -4.43711156e-01, -6.50832919e-01],
        [-2.68213297e-01, -8.66743750e-01, -8.84828071e-01,
         -3.25648815e+00,  2.31946842

In [183]:
data.sum(axis=0)

array([[-3.01271704,  4.40465526,  1.36848076, -0.58701654, -0.23778871,
        -1.17522063,  0.80232397,  0.16055923,  2.00648528, -0.83283983,
         0.73524522, -2.82535329, -1.62498492, -0.47293409, -1.57124789],
       [ 0.03553959,  0.05379189, -0.25360253,  1.7766262 , -2.03868867,
         0.59838312,  5.47016004, -2.57412712,  1.15027978,  3.38548989,
         1.88096172, -1.94727534,  3.37913336,  5.49770771,  0.98819214],
       [ 2.49974969,  0.50964171,  1.35596886,  0.11654414,  1.63494991,
         2.10299193,  3.44770707,  0.77337395,  3.56342717,  1.4323739 ,
        -0.36330016, -0.02369847, -0.87583675,  0.37113724,  0.48699262],
       [ 0.10920321,  1.66646192,  1.47908868, -1.54964539, -0.63752609,
         1.15811381,  0.77015899,  0.83196903, -2.51999725, -0.07986285,
         0.1452954 ,  0.03712709, -3.45812567, -0.29309692, -3.43903343],
       [ 0.41066948, -2.46064183,  2.36208047,  1.54811272, -2.16187805,
         1.22704479,  1.07772309,  0.72507172, 

In [185]:
data.sum(axis=(0,2)).shape

(10,)

In [187]:
data.sum()

20.23922296277951

In [189]:
data.sum(axis=(0,2))

array([-2.86235321, 17.40257179, 17.03202282, -5.77986948,  5.19077075,
       -4.19034981, -5.90074065, -7.27003291, -0.86306743,  7.48027109])

In [191]:
data = np.arange(1,10).reshape(3,3)

In [193]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [199]:
data = np.arange(1,15).reshape(7,2)

In [201]:
data

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [205]:
data.sum(axis=0)

array([49, 56])

In [207]:
data.sum(axis=1)

array([ 3,  7, 11, 15, 19, 23, 27])