In [1]:
import numpy as np

In [11]:
# How to create an empty and a full NumPy array?
empty_array = np.empty((3,4))
print("empty_array \n",empty_array)

full_array = np.full((3,4),5)
print("full_array \n",full_array)

empty_array 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
full_array 
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [15]:
# Create a Numpy array filled with all zeros
zero_array = np.zeros((3,5))
print("zeroArray")

zeroArray


In [17]:
zero_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
# Create a Numpy array filled with all ones
ones_array = np.ones((4,4))

In [21]:
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
# Check whether a Numpy array contains a specified row
data1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
row1 = np.array([4,5,6])

In [25]:
row1 in data1

True

In [29]:
# How to Remove rows in Numpy array that contains non-numeric values?
arr = np.array([
    [1.0, 2.0, 3.0],
    [4.0, np.nan, 6.0],
    [7.0, 8.0, 9.0],
    [np.inf, 11.0, 12.0]
])

In [31]:
new_arr = arr[np.all(np.isfinite(arr),axis=1)]

In [33]:
new_arr

array([[1., 2., 3.],
       [7., 8., 9.]])

In [37]:
# Remove single-dimensional entries from the shape of an array
arr = np.array([[[1,2,3]]])

In [39]:
arr.squeeze()

array([1, 2, 3])

In [43]:
# Find the number of occurrences of a sequence in a NumPy array
arr = np.array([1, 2, 3, 4, 2, 3, 4, 5])
sequence = np.array([2, 3, 4])

In [47]:
sliding_windows = np.lib.stride_tricks.sliding_window_view(arr, window_shape=len(sequence))
matches = np.all(sliding_windows == sequence, axis=1)
count = np.sum(matches)

In [49]:
count

2

In [73]:
# Find the most frequent value in a NumPy array
arr = np.array([1,1,1,1,2,2,2,2,2,3,4,5,6,6,6,4,4,4,4,8,8,8,8,6,7,6,6,5,5,5,5,5,5,9])
print(arr.shape)

(34,)


In [87]:
k = arr[0]
count1 = 1
max_count = 0
max_index = -1

for x in range(1,arr.shape[0]):
    if arr[x]==k:
        count1 += 1
    else:
        if max_count<count1:
            max_count = count1
            max_index = x-1
        count1 = 1
        k = arr[x]
if max_count < count1:
    max_count = count1
    max_index = arr.shape[0] - 1
arr[max_index]

5

In [111]:
# Combining a one and a two-dimensional NumPy Array
oneD_arr = np.array([1,2,3])
twoD_arr = np.array([[4,5,6],[7,8,9]])
combine_arr = np.vstack((oneD_arr,twoD_arr))
combine_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [113]:
# How to check whether specified values are present in NumPy array?
x = 4
x in combine_arr

True

In [159]:
# How to get all 2D diagonals of a 3D NumPy array?
arr = np.array([[[1,2,3],[5,6,7],[9,10,11]],[[13,14,15],[17,18,19],[21,22,23]],[[25,26,27],[29,30,31],[33,34,35]]])
arr

array([[[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]],

       [[13, 14, 15],
        [17, 18, 19],
        [21, 22, 23]],

       [[25, 26, 27],
        [29, 30, 31],
        [33, 34, 35]]])

In [161]:
arr.shape

(3, 3, 3)

In [163]:
arr[0]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [177]:
diagonal_arr= [layer.diagonal() for layer in arr]
diagonal_arr

[array([ 1,  6, 11]), array([13, 18, 23]), array([25, 30, 35])]

In [179]:
diagonal_anti_arr = [np.fliplr(layer).diagonal() for layer in arr]
diagonal_anti_arr

[array([3, 6, 9]), array([15, 18, 21]), array([27, 30, 33])]

In [187]:
# Flatten a Matrix in Python using NumPy
np.hstack(np.array([np.hstack(layer) for layer in arr]))

array([ 1,  2,  3,  5,  6,  7,  9, 10, 11, 13, 14, 15, 17, 18, 19, 21, 22,
       23, 25, 26, 27, 29, 30, 31, 33, 34, 35])

In [189]:
arr.ravel()

array([ 1,  2,  3,  5,  6,  7,  9, 10, 11, 13, 14, 15, 17, 18, 19, 21, 22,
       23, 25, 26, 27, 29, 30, 31, 33, 34, 35])

In [191]:
arr.flatten()

array([ 1,  2,  3,  5,  6,  7,  9, 10, 11, 13, 14, 15, 17, 18, 19, 21, 22,
       23, 25, 26, 27, 29, 30, 31, 33, 34, 35])

In [233]:
# Move axes of an array to new positions
arr = np.arange(24).reshape(2, 3, 4)

In [241]:
arr.shape

(2, 3, 4)

In [243]:
np.transpose(arr, axes=(1, 2, 0))

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [245]:
np.moveaxis(arr,2,1)

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

In [249]:
# NumPy – Fibonacci Series using Binet Formula
import math
phi = (1+math.sqrt(5))/2
psi = (1-math.sqrt(5))/2
def binetFibonacci(n):
    return round((phi**n - psi**n)/math.sqrt(5))

print(binetFibonacci(6))

8


In [251]:
binetFibonacci = np.vectorize(binetFibonacci)
binetFibonacci(np.arange(24))

array([    0,     1,     1,     2,     3,     5,     8,    13,    21,
          34,    55,    89,   144,   233,   377,   610,   987,  1597,
        2584,  4181,  6765, 10946, 17711, 28657])

In [297]:
# Counts the number of non-zero values in the array
x = np.round(np.random.rand(3,3)*np.random.rand(3,3)*10)
x

array([[4., 7., 3.],
       [3., 0., 3.],
       [1., 1., 1.]])

In [299]:
x!=0

array([[ True,  True,  True],
       [ True, False,  True],
       [ True,  True,  True]])

In [303]:
x[x!=0].size

8

In [305]:
count_non_zero = np.count_nonzero(x)
print(count_non_zero)

8


In [307]:
# Count the number of elements along a given axis
count_col = np.count_nonzero(x,axis=0)
count_col

array([3, 2, 3])

In [309]:
count_row = np.count_nonzero(x,axis=1)
count_row

array([3, 2, 3])

In [317]:
y = np.round(np.random.rand(10)*np.random.rand(10)*10)
y

array([5., 0., 5., 1., 1., 1., 2., 2., 3., 0.])

In [319]:
# Trim the leading and/or trailing zeros from a 1-D array
np.trim_zeros(y)

array([5., 0., 5., 1., 1., 1., 2., 2., 3.])

In [321]:
# Change data type of given numpy array
z = np.array(y,dtype=np.int32)
z

array([5, 0, 5, 1, 1, 1, 2, 2, 3, 0], dtype=int32)

In [325]:
# Reverse a numpy array
rev = z[::-1]
rev

array([0, 3, 2, 2, 1, 1, 1, 5, 0, 5], dtype=int32)

In [327]:
# How to make a NumPy array read-only?
rev.setflags(write=False)

In [331]:
rev[9]=7

ValueError: assignment destination is read-only

In [333]:
# Matrix numpy

In [335]:
# Get the maximum value from given matrix
a = np.matrix(np.array(np.round(np.random.rand(4,4)*np.random.rand(4,4)*10),dtype=np.int32))
a

matrix([[0, 4, 0, 1],
        [1, 2, 2, 2],
        [1, 7, 9, 4],
        [2, 2, 3, 1]], dtype=int32)

In [337]:
np.max(a)

9

In [339]:
np.min(a)

0

In [341]:
# Find the number of rows and columns of a given matrix using NumPy
a.shape

(4, 4)

In [343]:
# Find the sum of values in a matrix
np.sum(a)

41

In [347]:
# Calculate the sum of the diagonal elements of a NumPy array
np.sum(np.diagonal(a))

12

In [349]:
np.sum(np.fliplr(a).diagonal())

12

In [351]:
# Adding and Subtracting Matrices in Python
b = np.matrix(np.array(np.round(np.random.rand(4,4)*np.random.rand(4,4)*10),dtype=np.int32))
b

matrix([[0, 0, 4, 8],
        [2, 2, 1, 2],
        [3, 4, 0, 3],
        [4, 2, 7, 2]], dtype=int32)

In [353]:
a+b

matrix([[ 0,  4,  4,  9],
        [ 3,  4,  3,  4],
        [ 4, 11,  9,  7],
        [ 6,  4, 10,  3]], dtype=int32)

In [365]:
np.add(a,b)

matrix([[ 0,  4,  4,  9],
        [ 3,  4,  3,  4],
        [ 4, 11,  9,  7],
        [ 6,  4, 10,  3]], dtype=int32)

In [367]:
a-b

matrix([[ 0,  4, -4, -7],
        [-1,  0,  1,  0],
        [-2,  3,  9,  1],
        [-2,  0, -4, -1]], dtype=int32)

In [369]:
np.subtract(a,b)

matrix([[ 0,  4, -4, -7],
        [-1,  0,  1,  0],
        [-2,  3,  9,  1],
        [-2,  0, -4, -1]], dtype=int32)

In [393]:
# Ways to add row/columns in numpy array
[np.sum(np.array(layer)) for layer in a] # Row

[5, 7, 21, 8]

In [395]:
[np.sum(np.array(layer)) for layer in np.transpose(a)] #Column

[4, 15, 14, 8]

In [401]:
np.sum(a, axis=0)# Column

matrix([[ 4, 15, 14,  8]])

In [403]:
np.sum(a, axis=1)# Row

matrix([[ 5],
        [ 7],
        [21],
        [ 8]])

In [405]:
# Matrix Multiplication in NumPy
a*b

matrix([[12, 10, 11, 10],
        [18, 16, 20, 22],
        [57, 58, 39, 57],
        [17, 18, 17, 31]], dtype=int32)

In [407]:
a

matrix([[0, 4, 0, 1],
        [1, 2, 2, 2],
        [1, 7, 9, 4],
        [2, 2, 3, 1]], dtype=int32)

In [409]:
b

matrix([[0, 0, 4, 8],
        [2, 2, 1, 2],
        [3, 4, 0, 3],
        [4, 2, 7, 2]], dtype=int32)

In [411]:
b*a

matrix([[20, 44, 60, 24],
        [ 7, 23, 19, 12],
        [10, 26, 17, 14],
        [13, 73, 73, 38]], dtype=int32)

In [415]:
a.dot(b)

matrix([[12, 10, 11, 10],
        [18, 16, 20, 22],
        [57, 58, 39, 57],
        [17, 18, 17, 31]], dtype=int32)

In [417]:
b.dot(a)

matrix([[20, 44, 60, 24],
        [ 7, 23, 19, 12],
        [10, 26, 17, 14],
        [13, 73, 73, 38]], dtype=int32)

In [425]:
# Get the eigen values of a matrix
eigenvalues, eigenvectors = np.linalg.eig(a)
eigenvalues

array([12.32807806+0.j        ,  2.17671046+0.j        ,
       -1.25239426+0.96347284j, -1.25239426-0.96347284j])

In [427]:
eigenvectors

matrix([[ 0.10450097+0.j        , -0.70366465+0.j        ,
         -0.4411034 +0.42293989j, -0.4411034 -0.42293989j],
        [ 0.24606239+0.j        , -0.3186568 +0.j        ,
         -0.14320402-0.23866966j, -0.14320402+0.23866966j],
        [ 0.91437877+0.j        ,  0.58072433+0.j        ,
         -0.14935482+0.10766738j, -0.14935482-0.10766738j],
        [ 0.30404655+0.j        , -0.257047  +0.j        ,
          0.71776035+0.j        ,  0.71776035-0.j        ]])

In [429]:
# How to Calculate the determinant of a matrix using NumPy?
np.linalg.det(a)

66.99999999999997

In [433]:
# How to inverse a matrix using NumPy
np.linalg.inv(a)

matrix([[ 0.02985075,  0.13432836, -0.20895522,  0.53731343],
        [ 0.28358209, -0.2238806 ,  0.01492537,  0.10447761],
        [-0.1641791 , -0.23880597,  0.14925373,  0.04477612],
        [-0.13432836,  0.89552239, -0.05970149, -0.41791045]])

In [435]:
# How to count the frequency of unique values in NumPy array?
np.unique(a, return_counts=True)

(matrix([[0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 4, 4, 7, 9]], dtype=int32),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [447]:
# Multiply matrices of complex numbers using NumPy in Python
x = np.matrix(np.round([[8.5572191+01.5829756j, 09.1874805+04.3182391j, 01.2876313+05.1222221j],
 [002.486378+02.7310213j, 08.0921419+06.9521217j, 02.8446565+08.9596348j]]))
y = np.matrix(np.round([[002.89901 +04.6500811j, 06.5250314+09.7842826j, 08.5902412+004.081894j, 02.4791095+09.9347612j],
 [02.6727422+01.4351523j, 04.662008 +09.616372j , 08.9607831+09.3086584j, 004.122283+01.349505j ],
 [09.0827722+09.4164394j, 01.3147812+02.5536031j, 07.8311733+008.866497j, 03.6823746+01.2125719j]]))


In [449]:
x

matrix([[9.+2.j, 9.+4.j, 1.+5.j],
        [2.+3.j, 8.+7.j, 3.+9.j]])

In [451]:
y

matrix([[3. +5.j, 7.+10.j, 9. +4.j, 2.+10.j],
        [3. +1.j, 5.+10.j, 9. +9.j, 4. +1.j],
        [9. +9.j, 1. +3.j, 8. +9.j, 4. +1.j]])

In [453]:
x*y

matrix([[  4.+126.j,  34.+222.j,  81.+220.j,  29.+140.j],
        [-46.+156.j, -70.+174.j, -42.+269.j,   2.+101.j]])

In [455]:
x.dot(y)

matrix([[  4.+126.j,  34.+222.j,  81.+220.j,  29.+140.j],
        [-46.+156.j, -70.+174.j, -42.+269.j,   2.+101.j]])

In [461]:
# Compute the outer product of two given vectors using NumPy in Python
p = np.round(np.random.rand(1,3)*10)
q = np.round(np.random.rand(1,3)*10)

In [463]:
p

array([[4., 1., 3.]])

In [465]:
q

array([[5., 8., 3.]])

In [467]:
np.outer(p,q)

array([[20., 32., 12.],
       [ 5.,  8.,  3.],
       [15., 24.,  9.]])

In [469]:
# Outer[i][j] = p[i]*q[j]

In [475]:
# Calculate inner, outer, and cross products of matrices and vectors using NumPy
# inner = p1*q1+p2*q2+p3*q3
np.inner(p,q)

array([[37.]])

In [477]:
# pxq = [(p2q3-p3q2),(-p1q3+p3q1),(p1q2-q1p2)]
np.cross(p,q)

array([[-21.,   3.,  27.]])

In [479]:
# Compute the Kronecker product of two mulitdimension NumPy arrays
m = np.round(np.random.rand(2,2)*10)
n = np.round(np.random.rand(2,2)*10)

In [481]:
m

array([[1., 8.],
       [0., 4.]])

In [483]:
n

array([[8., 2.],
       [4., 6.]])

In [485]:
np.kron(m,n)

array([[ 8.,  2., 64., 16.],
       [ 4.,  6., 32., 48.],
       [ 0.,  0., 32.,  8.],
       [ 0.,  0., 16., 24.]])

In [489]:
# Convert covariance matrix to correlation matrix using Python
np.cov(a,b)

array([[ 3.58333333,  0.41666667,  1.91666667, -0.33333333, -2.33333333,
         0.41666667,  2.16666667, -2.91666667],
       [ 0.41666667,  0.25      ,  1.41666667,  0.        ,  1.        ,
        -0.08333333, -0.16666667, -0.08333333],
       [ 1.91666667,  1.41666667, 12.25      ,  1.66666667,  1.66666667,
        -1.25      , -3.16666667,  3.41666667],
       [-0.33333333,  0.        ,  1.66666667,  0.66666667, -1.33333333,
        -0.33333333, -1.        ,  1.66666667],
       [-2.33333333,  1.        ,  1.66666667, -1.33333333, 14.66666667,
        -0.33333333, -2.        , -0.33333333],
       [ 0.41666667, -0.08333333, -1.25      , -0.33333333, -0.33333333,
         0.25      ,  0.83333333, -1.08333333],
       [ 2.16666667, -0.16666667, -3.16666667, -1.        , -2.        ,
         0.83333333,  3.        , -3.83333333],
       [-2.91666667, -0.08333333,  3.41666667,  1.66666667, -0.33333333,
        -1.08333333, -3.83333333,  5.58333333]])

In [493]:
# Convert the matrix into a list
list(p)

[array([4., 1., 3.])]

In [495]:
# Questions on NumPy Indexing
# --------------------------

In [501]:
# Replace NumPy array elements that doesn’t satisfy the given condition
A = np.array(np.round(np.random.rand(1,10)*10),dtype = np.int32)
A

array([[3, 7, 2, 7, 9, 3, 4, 4, 4, 6]], dtype=int32)

In [503]:
# Method 1: Using Boolean Indexing
A[A%2!=0]=0

In [505]:
A

array([[0, 0, 2, 0, 0, 0, 4, 4, 4, 6]], dtype=int32)

In [509]:
#Method 2: Using Where
np.where(A!=0,A,-1)

array([[-1, -1,  2, -1, -1, -1,  4,  4,  4,  6]], dtype=int32)

In [511]:
# Return the indices of elements where the given condition is satisfied
A = np.array(np.round(np.random.rand(1,10)*10),dtype = np.int32)
A

array([[ 8,  9,  1, 10,  6,  2,  9,  5,  2,  8]], dtype=int32)

In [517]:
# Method1: Using Where
np.where(A>5)

(array([0, 0, 0, 0, 0, 0]), array([0, 1, 3, 4, 6, 9]))

In [519]:
# Method2: Using non zero
np.nonzero(A>5)

(array([0, 0, 0, 0, 0, 0]), array([0, 1, 3, 4, 6, 9]))

In [527]:
# Replace NaN values with average of columns
B = np.array(np.round(np.random.rand(4,5)*10))
B

array([[ 0.,  6.,  9.,  3.,  3.],
       [ 3.,  9., 10.,  9.,  2.],
       [ 9.,  5.,  2.,  6.,  7.],
       [ 3.,  4.,  3.,  6.,  5.]])

In [529]:
np.average(B,axis=0)

array([3.75, 6.  , 6.  , 6.  , 4.25])

In [531]:
B[3][4] = np.NaN
B[1][3] = np.NaN
B[2][1] = np.NaN

In [541]:
col_mean = np.nanmean(B,axis=0)
col_mean

array([3.75      , 6.33333333, 6.        , 5.        , 4.        ])

In [545]:
B[(np.isnan(B))]=np.take(col_mean,np.where(np.isnan(B))[1])
B

array([[ 0.        ,  6.        ,  9.        ,  3.        ,  3.        ],
       [ 3.        ,  9.        , 10.        ,  5.        ,  2.        ],
       [ 9.        ,  6.33333333,  2.        ,  6.        ,  7.        ],
       [ 3.        ,  4.        ,  3.        ,  6.        ,  4.        ]])

In [551]:
# Replace negative value with zero in numpy array
B[3][4] = B[3][4]* -1
B[1][3] = B[1][3]* -1
B[2][1] = B[2][1]* -1
B[B<0] = 0

In [553]:
B

array([[ 0.,  6.,  9.,  3.,  3.],
       [ 3.,  9., 10.,  0.,  2.],
       [ 9.,  0.,  2.,  6.,  7.],
       [ 3.,  4.,  3.,  6.,  0.]])

In [555]:
# How to get values of an NumPy array at certain index positions?
B[3][1]

4.0

In [561]:
# Find indices of elements equal to zero in a NumPy array
np.where(B==0)

(array([0, 1, 2, 3]), array([0, 3, 1, 4]))

In [565]:
# How to access different rows of a multidimensional NumPy array?
# advance
B[[1,3]]

array([[ 3.,  9., 10.,  0.,  2.],
       [ 3.,  4.,  3.,  6.,  0.]])

In [567]:
# Get row numbers of NumPy array having element larger than X
X = 6
np.where(B>X)[0]

array([0, 1, 1, 2, 2])

In [575]:
# Check elements present in the NumPy array
10 in B

True

In [579]:
# Combined array index by index
np.stack((m,n),axis = 1)

array([[[1., 8.],
        [8., 2.]],

       [[0., 4.],
        [4., 6.]]])

In [587]:
np.concatenate((n,m),axis=0)

array([[8., 2.],
       [4., 6.],
       [1., 8.],
       [0., 4.]])

In [589]:
m+n

array([[ 9., 10.],
       [ 4., 10.]])

In [591]:
# Questions on NumPy Sorting and Searching
# --------------------------

In [595]:
# How to get the indices of the sorted array using NumPy in Python?
C = np.array(np.round(np.random.rand(1,10)*10),dtype=np.int32)
C

array([[ 7,  9,  2,  3,  4,  5, 10,  9,  9,  0]], dtype=int32)

In [601]:
np.argsort(C)

array([[9, 2, 3, 4, 5, 0, 1, 7, 8, 6]])

In [631]:
# Finding the k smallest values of a NumPy array
# Method1: Partition
k = 4
smallest_k = np.partition(C, k)[:k]

In [633]:
smallest_k

array([[ 0,  3,  2,  4,  5,  7,  9,  9,  9, 10]], dtype=int32)

In [635]:
# Method2: argsort()
arr[np.argsort(C)[k:]]

array([], shape=(0, 10, 3, 4), dtype=int64)