In [7]:
import numpy as np

In [9]:
# How to create an empty and a full NumPy array?
empty_array = np.empty((3,4))
print("empty_array \n",empty_array)

full_array = np.full((3,4),5)
print("full_array \n",full_array)

empty_array 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
full_array 
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [11]:
# Create a Numpy array filled with all zeros
zero_array = np.zeros((3,5))
print("zeroArray")

zeroArray


In [13]:
zero_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
# Create a Numpy array filled with all ones
ones_array = np.ones((4,4))

In [17]:
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
# Check whether a Numpy array contains a specified row
data1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
row1 = np.array([4,5,6])

In [21]:
row1 in data1

True

In [23]:
# How to Remove rows in Numpy array that contains non-numeric values?
arr = np.array([
    [1.0, 2.0, 3.0],
    [4.0, np.nan, 6.0],
    [7.0, 8.0, 9.0],
    [np.inf, 11.0, 12.0]
])

In [25]:
new_arr = arr[np.all(np.isfinite(arr),axis=1)]

In [27]:
new_arr

array([[1., 2., 3.],
       [7., 8., 9.]])

In [29]:
# Remove single-dimensional entries from the shape of an array
arr = np.array([[[1,2,3]]])

In [31]:
arr.squeeze()

array([1, 2, 3])

In [33]:
# Find the number of occurrences of a sequence in a NumPy array
arr = np.array([1, 2, 3, 4, 2, 3, 4, 5])
sequence = np.array([2, 3, 4])

In [35]:
sliding_windows = np.lib.stride_tricks.sliding_window_view(arr, window_shape=len(sequence))
matches = np.all(sliding_windows == sequence, axis=1)
count = np.sum(matches)

In [37]:
count

2

In [39]:
# Find the most frequent value in a NumPy array
arr = np.array([1,1,1,1,2,2,2,2,2,3,4,5,6,6,6,4,4,4,4,8,8,8,8,6,7,6,6,5,5,5,5,5,5,9])
print(arr.shape)

(34,)


In [41]:
k = arr[0]
count1 = 1
max_count = 0
max_index = -1

for x in range(1,arr.shape[0]):
    if arr[x]==k:
        count1 += 1
    else:
        if max_count<count1:
            max_count = count1
            max_index = x-1
        count1 = 1
        k = arr[x]
if max_count < count1:
    max_count = count1
    max_index = arr.shape[0] - 1
arr[max_index]

5

In [43]:
# Combining a one and a two-dimensional NumPy Array
oneD_arr = np.array([1,2,3])
twoD_arr = np.array([[4,5,6],[7,8,9]])
combine_arr = np.vstack((oneD_arr,twoD_arr))
combine_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
# How to check whether specified values are present in NumPy array?
x = 4
x in combine_arr

True

In [47]:
# How to get all 2D diagonals of a 3D NumPy array?
arr = np.array([[[1,2,3],[5,6,7],[9,10,11]],[[13,14,15],[17,18,19],[21,22,23]],[[25,26,27],[29,30,31],[33,34,35]]])
arr

array([[[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]],

       [[13, 14, 15],
        [17, 18, 19],
        [21, 22, 23]],

       [[25, 26, 27],
        [29, 30, 31],
        [33, 34, 35]]])

In [49]:
arr.shape

(3, 3, 3)

In [51]:
arr[0]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [53]:
diagonal_arr= [layer.diagonal() for layer in arr]
diagonal_arr

[array([ 1,  6, 11]), array([13, 18, 23]), array([25, 30, 35])]

In [55]:
diagonal_anti_arr = [np.fliplr(layer).diagonal() for layer in arr]
diagonal_anti_arr

[array([3, 6, 9]), array([15, 18, 21]), array([27, 30, 33])]

In [57]:
# Flatten a Matrix in Python using NumPy
np.hstack(np.array([np.hstack(layer) for layer in arr]))

array([ 1,  2,  3,  5,  6,  7,  9, 10, 11, 13, 14, 15, 17, 18, 19, 21, 22,
       23, 25, 26, 27, 29, 30, 31, 33, 34, 35])

In [59]:
arr.ravel()

array([ 1,  2,  3,  5,  6,  7,  9, 10, 11, 13, 14, 15, 17, 18, 19, 21, 22,
       23, 25, 26, 27, 29, 30, 31, 33, 34, 35])

In [61]:
arr.flatten()

array([ 1,  2,  3,  5,  6,  7,  9, 10, 11, 13, 14, 15, 17, 18, 19, 21, 22,
       23, 25, 26, 27, 29, 30, 31, 33, 34, 35])

In [63]:
# Move axes of an array to new positions
arr = np.arange(24).reshape(2, 3, 4)

In [65]:
arr.shape

(2, 3, 4)

In [67]:
np.transpose(arr, axes=(1, 2, 0))

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [69]:
np.moveaxis(arr,2,1)

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

In [71]:
# NumPy – Fibonacci Series using Binet Formula
import math
phi = (1+math.sqrt(5))/2
psi = (1-math.sqrt(5))/2
def binetFibonacci(n):
    return round((phi**n - psi**n)/math.sqrt(5))

print(binetFibonacci(6))

8


In [73]:
binetFibonacci = np.vectorize(binetFibonacci)
binetFibonacci(np.arange(24))

array([    0,     1,     1,     2,     3,     5,     8,    13,    21,
          34,    55,    89,   144,   233,   377,   610,   987,  1597,
        2584,  4181,  6765, 10946, 17711, 28657])

In [75]:
# Counts the number of non-zero values in the array
x = np.round(np.random.rand(3,3)*np.random.rand(3,3)*10)
x

array([[3., 7., 2.],
       [4., 2., 2.],
       [2., 1., 1.]])

In [77]:
x!=0

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [79]:
x[x!=0].size

9

In [81]:
count_non_zero = np.count_nonzero(x)
print(count_non_zero)

9


In [83]:
# Count the number of elements along a given axis
count_col = np.count_nonzero(x,axis=0)
count_col

array([3, 3, 3])

In [85]:
count_row = np.count_nonzero(x,axis=1)
count_row

array([3, 3, 3])

In [87]:
y = np.round(np.random.rand(10)*np.random.rand(10)*10)
y

array([7., 7., 1., 7., 1., 1., 5., 1., 2., 3.])

In [89]:
# Trim the leading and/or trailing zeros from a 1-D array
np.trim_zeros(y)

array([7., 7., 1., 7., 1., 1., 5., 1., 2., 3.])

In [91]:
# Change data type of given numpy array
z = np.array(y,dtype=np.int32)
z

array([7, 7, 1, 7, 1, 1, 5, 1, 2, 3], dtype=int32)

In [93]:
# Reverse a numpy array
rev = z[::-1]
rev

array([3, 2, 1, 5, 1, 1, 7, 1, 7, 7], dtype=int32)

In [95]:
# How to make a NumPy array read-only?
rev.setflags(write=False)

In [97]:
rev[9]=7

ValueError: assignment destination is read-only

In [99]:
# Matrix numpy

In [101]:
# Get the maximum value from given matrix
a = np.matrix(np.array(np.round(np.random.rand(4,4)*np.random.rand(4,4)*10),dtype=np.int32))
a

matrix([[2, 0, 4, 4],
        [5, 0, 9, 3],
        [2, 2, 1, 6],
        [5, 3, 2, 3]], dtype=int32)

In [103]:
np.max(a)

9

In [105]:
np.min(a)

0

In [107]:
# Find the number of rows and columns of a given matrix using NumPy
a.shape

(4, 4)

In [109]:
# Find the sum of values in a matrix
np.sum(a)

51

In [111]:
# Calculate the sum of the diagonal elements of a NumPy array
np.sum(np.diagonal(a))

6

In [113]:
np.sum(np.fliplr(a).diagonal())

20

In [115]:
# Adding and Subtracting Matrices in Python
b = np.matrix(np.array(np.round(np.random.rand(4,4)*np.random.rand(4,4)*10),dtype=np.int32))
b

matrix([[1, 0, 1, 1],
        [2, 1, 0, 1],
        [3, 3, 2, 2],
        [1, 2, 3, 0]], dtype=int32)

In [117]:
a+b

matrix([[3, 0, 5, 5],
        [7, 1, 9, 4],
        [5, 5, 3, 8],
        [6, 5, 5, 3]], dtype=int32)

In [119]:
np.add(a,b)

matrix([[3, 0, 5, 5],
        [7, 1, 9, 4],
        [5, 5, 3, 8],
        [6, 5, 5, 3]], dtype=int32)

In [121]:
a-b

matrix([[ 1,  0,  3,  3],
        [ 3, -1,  9,  2],
        [-1, -1, -1,  4],
        [ 4,  1, -1,  3]], dtype=int32)

In [123]:
np.subtract(a,b)

matrix([[ 1,  0,  3,  3],
        [ 3, -1,  9,  2],
        [-1, -1, -1,  4],
        [ 4,  1, -1,  3]], dtype=int32)

In [125]:
# Ways to add row/columns in numpy array
[np.sum(np.array(layer)) for layer in a] # Row

[10, 17, 11, 13]

In [127]:
[np.sum(np.array(layer)) for layer in np.transpose(a)] #Column

[14, 5, 16, 16]

In [129]:
np.sum(a, axis=0)# Column

matrix([[14,  5, 16, 16]])

In [131]:
np.sum(a, axis=1)# Row

matrix([[10],
        [17],
        [11],
        [13]])

In [133]:
# Matrix Multiplication in NumPy
a*b

matrix([[18, 20, 22, 10],
        [35, 33, 32, 23],
        [15, 17, 22,  6],
        [20, 15, 18, 12]], dtype=int32)

In [135]:
a

matrix([[2, 0, 4, 4],
        [5, 0, 9, 3],
        [2, 2, 1, 6],
        [5, 3, 2, 3]], dtype=int32)

In [137]:
b

matrix([[1, 0, 1, 1],
        [2, 1, 0, 1],
        [3, 3, 2, 2],
        [1, 2, 3, 0]], dtype=int32)

In [139]:
b*a

matrix([[ 9,  5,  7, 13],
        [14,  3, 19, 14],
        [35, 10, 45, 39],
        [18,  6, 25, 28]], dtype=int32)

In [141]:
a.dot(b)

matrix([[18, 20, 22, 10],
        [35, 33, 32, 23],
        [15, 17, 22,  6],
        [20, 15, 18, 12]], dtype=int32)

In [143]:
b.dot(a)

matrix([[ 9,  5,  7, 13],
        [14,  3, 19, 14],
        [35, 10, 45, 39],
        [18,  6, 25, 28]], dtype=int32)

In [145]:
# Get the eigen values of a matrix
eigenvalues, eigenvectors = np.linalg.eig(a)
eigenvalues

array([12.14479437+0.j        , -3.19095679+3.15568267j,
       -3.19095679-3.15568267j,  0.23711922+0.j        ])

In [147]:
eigenvectors

matrix([[-0.38130325+0.j        ,  0.23125457+0.28487421j,
          0.23125457-0.28487421j,  0.53085793+0.j        ],
        [-0.62081759+0.j        ,  0.70673582+0.j        ,
          0.70673582-0.j        , -0.75967759+0.j        ],
        [-0.45533391+0.j        , -0.30614709+0.22793595j,
         -0.30614709-0.22793595j, -0.35542406+0.j        ],
        [-0.51172685+0.j        , -0.21870418-0.41518686j,
         -0.21870418+0.41518686j,  0.12146425+0.j        ]])

In [149]:
# How to Calculate the determinant of a matrix using NumPy?
np.linalg.det(a)

57.999999999999986

In [151]:
# How to inverse a matrix using NumPy
np.linalg.inv(a)

matrix([[ 1.9137931 , -0.89655172, -1.24137931,  0.82758621],
        [-2.89655172,  1.27586207,  1.68965517, -0.79310345],
        [-1.24137931,  0.68965517,  0.72413793, -0.48275862],
        [ 0.53448276, -0.24137931, -0.10344828,  0.06896552]])

In [153]:
# How to count the frequency of unique values in NumPy array?
np.unique(a, return_counts=True)

(matrix([[0, 0, 1, 2, 2, 2, 2, 3, 3, 3, 4, 4, 5, 5, 6, 9]], dtype=int32),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [155]:
# Multiply matrices of complex numbers using NumPy in Python
x = np.matrix(np.round([[8.5572191+01.5829756j, 09.1874805+04.3182391j, 01.2876313+05.1222221j],
 [002.486378+02.7310213j, 08.0921419+06.9521217j, 02.8446565+08.9596348j]]))
y = np.matrix(np.round([[002.89901 +04.6500811j, 06.5250314+09.7842826j, 08.5902412+004.081894j, 02.4791095+09.9347612j],
 [02.6727422+01.4351523j, 04.662008 +09.616372j , 08.9607831+09.3086584j, 004.122283+01.349505j ],
 [09.0827722+09.4164394j, 01.3147812+02.5536031j, 07.8311733+008.866497j, 03.6823746+01.2125719j]]))


In [157]:
x

matrix([[9.+2.j, 9.+4.j, 1.+5.j],
        [2.+3.j, 8.+7.j, 3.+9.j]])

In [159]:
y

matrix([[3. +5.j, 7.+10.j, 9. +4.j, 2.+10.j],
        [3. +1.j, 5.+10.j, 9. +9.j, 4. +1.j],
        [9. +9.j, 1. +3.j, 8. +9.j, 4. +1.j]])

In [161]:
x*y

matrix([[  4.+126.j,  34.+222.j,  81.+220.j,  29.+140.j],
        [-46.+156.j, -70.+174.j, -42.+269.j,   2.+101.j]])

In [163]:
x.dot(y)

matrix([[  4.+126.j,  34.+222.j,  81.+220.j,  29.+140.j],
        [-46.+156.j, -70.+174.j, -42.+269.j,   2.+101.j]])

In [165]:
# Compute the outer product of two given vectors using NumPy in Python
p = np.round(np.random.rand(1,3)*10)
q = np.round(np.random.rand(1,3)*10)

In [167]:
p

array([[5., 3., 6.]])

In [169]:
q

array([[8., 3., 4.]])

In [171]:
np.outer(p,q)

array([[40., 15., 20.],
       [24.,  9., 12.],
       [48., 18., 24.]])

In [173]:
# Outer[i][j] = p[i]*q[j]

In [175]:
# Calculate inner, outer, and cross products of matrices and vectors using NumPy
# inner = p1*q1+p2*q2+p3*q3
np.inner(p,q)

array([[73.]])

In [177]:
# pxq = [(p2q3-p3q2),(-p1q3+p3q1),(p1q2-q1p2)]
np.cross(p,q)

array([[-6., 28., -9.]])

In [179]:
# Compute the Kronecker product of two mulitdimension NumPy arrays
m = np.round(np.random.rand(2,2)*10)
n = np.round(np.random.rand(2,2)*10)

In [181]:
m

array([[ 2., 10.],
       [ 3.,  4.]])

In [183]:
n

array([[4., 8.],
       [8., 9.]])

In [185]:
np.kron(m,n)

array([[ 8., 16., 40., 80.],
       [16., 18., 80., 90.],
       [12., 24., 16., 32.],
       [24., 27., 32., 36.]])

In [187]:
# Convert covariance matrix to correlation matrix using Python
np.cov(a,b)

array([[ 3.66666667,  5.16666667,  1.5       , -0.83333333,  0.83333333,
        -0.66666667, -1.        , -0.33333333],
       [ 5.16666667, 14.25      , -3.25      , -1.08333333,  1.41666667,
        -1.33333333, -1.16666667,  2.16666667],
       [ 1.5       , -3.25      ,  4.91666667,  0.08333333,  0.25      ,
         0.33333333, -0.5       , -2.5       ],
       [-0.83333333, -1.08333333,  0.08333333,  1.58333333,  0.08333333,
         1.        ,  0.5       , -0.83333333],
       [ 0.83333333,  1.41666667,  0.25      ,  0.08333333,  0.25      ,
         0.        , -0.16666667, -0.16666667],
       [-0.66666667, -1.33333333,  0.33333333,  1.        ,  0.        ,
         0.66666667,  0.33333333, -0.66666667],
       [-1.        , -1.16666667, -0.5       ,  0.5       , -0.16666667,
         0.33333333,  0.33333333,  0.        ],
       [-0.33333333,  2.16666667, -2.5       , -0.83333333, -0.16666667,
        -0.66666667,  0.        ,  1.66666667]])

In [189]:
# Convert the matrix into a list
list(p)

[array([5., 3., 6.])]

In [191]:
# Questions on NumPy Indexing
# --------------------------

In [193]:
# Replace NumPy array elements that doesn’t satisfy the given condition
A = np.array(np.round(np.random.rand(1,10)*10),dtype = np.int32)
A

array([[1, 2, 9, 7, 9, 8, 8, 9, 5, 8]], dtype=int32)

In [195]:
# Method 1: Using Boolean Indexing
A[A%2!=0]=0

In [197]:
A

array([[0, 2, 0, 0, 0, 8, 8, 0, 0, 8]], dtype=int32)

In [199]:
#Method 2: Using Where
np.where(A!=0,A,-1)

array([[-1,  2, -1, -1, -1,  8,  8, -1, -1,  8]], dtype=int32)

In [201]:
# Return the indices of elements where the given condition is satisfied
A = np.array(np.round(np.random.rand(1,10)*10),dtype = np.int32)
A

array([[ 7,  8,  0, 10,  8,  9,  8,  9,  3,  7]], dtype=int32)

In [203]:
# Method1: Using Where
np.where(A>5)

(array([0, 0, 0, 0, 0, 0, 0, 0]), array([0, 1, 3, 4, 5, 6, 7, 9]))

In [205]:
# Method2: Using non zero
np.nonzero(A>5)

(array([0, 0, 0, 0, 0, 0, 0, 0]), array([0, 1, 3, 4, 5, 6, 7, 9]))

In [207]:
# Replace NaN values with average of columns
B = np.array(np.round(np.random.rand(4,5)*10))
B

array([[10.,  6.,  6.,  1.,  1.],
       [ 4.,  3.,  5.,  1.,  3.],
       [ 3.,  1.,  0.,  7.,  2.],
       [ 1.,  1.,  2.,  0.,  1.]])

In [209]:
np.average(B,axis=0)

array([4.5 , 2.75, 3.25, 2.25, 1.75])

In [211]:
B[3][4] = np.NaN
B[1][3] = np.NaN
B[2][1] = np.NaN

In [213]:
col_mean = np.nanmean(B,axis=0)
col_mean

array([4.5       , 3.33333333, 3.25      , 2.66666667, 2.        ])

In [215]:
B[(np.isnan(B))]=np.take(col_mean,np.where(np.isnan(B))[1])
B

array([[10.        ,  6.        ,  6.        ,  1.        ,  1.        ],
       [ 4.        ,  3.        ,  5.        ,  2.66666667,  3.        ],
       [ 3.        ,  3.33333333,  0.        ,  7.        ,  2.        ],
       [ 1.        ,  1.        ,  2.        ,  0.        ,  2.        ]])

In [217]:
# Replace negative value with zero in numpy array
B[3][4] = B[3][4]* -1
B[1][3] = B[1][3]* -1
B[2][1] = B[2][1]* -1
B[B<0] = 0

In [219]:
B

array([[10.,  6.,  6.,  1.,  1.],
       [ 4.,  3.,  5.,  0.,  3.],
       [ 3.,  0.,  0.,  7.,  2.],
       [ 1.,  1.,  2.,  0.,  0.]])

In [221]:
# How to get values of an NumPy array at certain index positions?
B[3][1]

1.0

In [223]:
# Find indices of elements equal to zero in a NumPy array
np.where(B==0)

(array([1, 2, 2, 3, 3]), array([3, 1, 2, 3, 4]))

In [225]:
# How to access different rows of a multidimensional NumPy array?
# advance
B[[1,3]]

array([[4., 3., 5., 0., 3.],
       [1., 1., 2., 0., 0.]])

In [227]:
# Get row numbers of NumPy array having element larger than X
X = 6
np.where(B>X)[0]

array([0, 2])

In [229]:
# Check elements present in the NumPy array
10 in B

True

In [231]:
# Combined array index by index
np.stack((m,n),axis = 1)

array([[[ 2., 10.],
        [ 4.,  8.]],

       [[ 3.,  4.],
        [ 8.,  9.]]])

In [233]:
np.concatenate((n,m),axis=0)

array([[ 4.,  8.],
       [ 8.,  9.],
       [ 2., 10.],
       [ 3.,  4.]])

In [235]:
m+n

array([[ 6., 18.],
       [11., 13.]])

In [237]:
# Questions on NumPy Sorting and Searching
# --------------------------

In [311]:
# How to get the indices of the sorted array using NumPy in Python?
C = np.array(np.round(np.random.rand(10)*10),dtype=np.int32)
C

array([6, 9, 8, 0, 2, 6, 1, 4, 6, 8], dtype=int32)

In [313]:
np.argsort(C)

array([3, 6, 4, 7, 0, 5, 8, 2, 9, 1])

In [315]:
# Finding the k smallest values of a NumPy array
# Method1: Partition
k = 4
smallest_k = np.partition(C, k)[:k]

In [317]:
smallest_k

array([0, 1, 2, 4], dtype=int32)

In [325]:
# Method2: argsort()
C[np.argsort(C)[:k]]

array([0, 1, 2, 4], dtype=int32)

In [335]:
# How to get the n-largest values of an array using NumPy?
largest_k = C[np.argsort(C)[-k:]]

In [337]:
largest_k

array([6, 8, 8, 9], dtype=int32)

In [339]:
'''
The numpy.partition() function is used to partially sort an array along a specified axis. Specifically, it rearranges the elements of the array such that:

The element at the 
𝑘
k-th position (0-based index) is in the correct position in the sorted order of the array.
All elements before the 
𝑘
k-th position are smaller or equal to it.
All elements after the 
𝑘
k-th position are greater or equal to it.
The sorting is only partial, so the elements before and after the 
𝑘
k-th position are not necessarily sorted themselves.
'''


'\nThe numpy.partition() function is used to partially sort an array along a specified axis. Specifically, it rearranges the elements of the array such that:\n\nThe element at the \n𝑘\nk-th position (0-based index) is in the correct position in the sorted order of the array.\nAll elements before the \n𝑘\nk-th position are smaller or equal to it.\nAll elements after the \n𝑘\nk-th position are greater or equal to it.\nThe sorting is only partial, so the elements before and after the \n𝑘\nk-th position are not necessarily sorted themselves.\n'

In [341]:
'''

The numpy.argsort() function returns the indices that would sort an array. Instead of returning the sorted array itself, it provides the indices of the original array elements in sorted order.
'''

'\n\nThe numpy.argsort() function returns the indices that would sort an array. Instead of returning the sorted array itself, it provides the indices of the original array elements in sorted order.\n'

In [343]:
np.partition(C, k)[k:]

array([6, 6, 6, 9, 8, 8], dtype=int32)

In [345]:
# Sort the values in a matrix
C.sort()

In [347]:
C

array([0, 1, 2, 4, 6, 6, 6, 8, 8, 9], dtype=int32)

In [349]:
# Filter out integers from float numpy array
arr = np.array([1.2, 2.0, 3.5, 4.0, 5.8, 6.0])  # Float array with some integers
filtered = arr[np.modf(arr)[0] != 0]  # Keep only non-integer values

In [351]:
filtered

array([1.2, 3.5, 5.8])

In [355]:
# Find the indices into a sorted array
arr = np.array([40, 10, 30, 20])
indices = np.argsort(arr)

print(indices)

[1 3 2 0]


In [447]:
# How to get element-wise true division of an array using Numpy?
a = (np.random.rand(4,5)*10*np.random.randint(-1,2))
b = (np.random.rand(4,5)*10*np.random.randint(-1,2))

In [449]:
a

array([[-0.98571794, -9.99405431, -5.78471849, -4.28037207, -6.38748412],
       [-5.39698894, -7.82849251, -2.71218238, -2.85507212, -4.76015689],
       [-8.98994659, -6.39530621, -8.21509311, -6.80884685, -2.3628295 ],
       [-8.07765814, -2.7368419 , -5.67437493, -1.42001845, -3.25575213]])

In [451]:
b

array([[6.50450658, 4.88934137, 0.88822011, 5.05090535, 9.85858433],
       [0.2085724 , 5.49400231, 3.68088556, 6.29673803, 8.55835413],
       [1.34779555, 3.13562108, 7.95641022, 8.76775471, 6.22476398],
       [2.38481456, 2.60864059, 0.91338537, 3.82860847, 1.63238718]])

In [453]:
a/b

array([[ -0.15154384,  -2.0440492 ,  -6.51270831,  -0.8474465 ,
         -0.64791089],
       [-25.87585396,  -1.42491613,  -0.73682877,  -0.45342082,
         -0.55620004],
       [ -6.67011152,  -2.03956602,  -1.03251251,  -0.77657816,
         -0.3795854 ],
       [ -3.38712211,  -1.04914487,  -6.21246534,  -0.37089675,
         -1.99447298]])

In [455]:
# How to calculate the element-wise absolute value of NumPy array?
a = np.abs(a)
a

array([[0.98571794, 9.99405431, 5.78471849, 4.28037207, 6.38748412],
       [5.39698894, 7.82849251, 2.71218238, 2.85507212, 4.76015689],
       [8.98994659, 6.39530621, 8.21509311, 6.80884685, 2.3628295 ],
       [8.07765814, 2.7368419 , 5.67437493, 1.42001845, 3.25575213]])

In [457]:
# How to calculate the element-wise absolute value of NumPy array?
a = np.abs(a)
a

array([[0.98571794, 9.99405431, 5.78471849, 4.28037207, 6.38748412],
       [5.39698894, 7.82849251, 2.71218238, 2.85507212, 4.76015689],
       [8.98994659, 6.39530621, 8.21509311, 6.80884685, 2.3628295 ],
       [8.07765814, 2.7368419 , 5.67437493, 1.42001845, 3.25575213]])

In [461]:
# Compute the negative of the NumPy array
a = -a
a

array([[0.98571794, 9.99405431, 5.78471849, 4.28037207, 6.38748412],
       [5.39698894, 7.82849251, 2.71218238, 2.85507212, 4.76015689],
       [8.98994659, 6.39530621, 8.21509311, 6.80884685, 2.3628295 ],
       [8.07765814, 2.7368419 , 5.67437493, 1.42001845, 3.25575213]])

In [512]:
# Multiply 2d numpy array corresponding to 1d array
p = np.round(np.random.rand(5)*10)
q = np.round(np.random.rand(5,4)*10)

In [514]:
p

array([5., 0., 6., 3., 9.])

In [516]:
q

array([[2., 6., 5., 3.],
       [9., 4., 1., 6.],
       [5., 7., 5., 7.],
       [5., 5., 6., 9.],
       [2., 7., 3., 5.]])

In [520]:
p = p.reshape(p.shape[0],1)
print(p)
print(p*q)

[[5.]
 [0.]
 [6.]
 [3.]
 [9.]]
[[10. 30. 25. 15.]
 [ 0.  0.  0.  0.]
 [30. 42. 30. 42.]
 [15. 15. 18. 27.]
 [18. 63. 27. 45.]]


In [542]:
# Computes the inner product of two arrays
x = np.round(np.random.rand(1,5)*10)
y = np.round(np.random.rand(3,5)*10)
print(x)
print(y)
print(np.inner(x,y))

[[0. 5. 3. 1. 3.]]
[[1. 7. 4. 9. 4.]
 [1. 6. 3. 5. 7.]
 [2. 7. 9. 7. 3.]]
[[68. 65. 78.]]


In [526]:
# Compute the nth percentile of the NumPy array
n = 15
q * (15/100)

array([[0.3 , 0.9 , 0.75, 0.45],
       [1.35, 0.6 , 0.15, 0.9 ],
       [0.75, 1.05, 0.75, 1.05],
       [0.75, 0.75, 0.9 , 1.35],
       [0.3 , 1.05, 0.45, 0.75]])

In [548]:
# Calculate the n-th order discrete difference along the given axis
# The n-th order discrete difference is a measure of the difference between successive elements of an array, applied recursively. It computes the difference of an array's elements along a specified axis, and the operation can be applied multiple times (for n-th order difference).

# For example:

# First-order difference: Computes the difference between consecutive elements.
# Second-order difference: Computes the difference of the first-order differences, and so on.
# In NumPy, the function used for calculating the n-th order discrete difference is np.diff(). By specifying the n parameter, you can control how many times the difference is applied.

k = np.round(np.random.rand(10)*10)
x1 = np.diff(k,n=1)
print(k)
print(x1)
x2 = np.diff(k,n=2)
print(x2)

[9. 2. 5. 6. 9. 4. 4. 5. 9. 1.]
[-7.  3.  1.  3. -5.  0.  1.  4. -8.]
[ 10.  -2.   2.  -8.   5.   1.   3. -12.]


In [552]:
# Calculate the sum of all columns in a 2D NumPy array
g = np.round(np.random.rand(5,5)*10)
print(g)
np.sum(g,axis=0)

[[ 6.  5.  7.  2.  3.]
 [ 1.  7.  4. 10.  5.]
 [ 2.  9.  1.  2.  6.]
 [ 3.  2.  6.  0.  9.]
 [ 6.  8.  6.  2.  5.]]


array([18., 31., 24., 16., 28.])

In [562]:
# Calculate average values of two given NumPy arrays
p1 = np.round(np.random.rand(4,4)*10)
p2 = np.round(np.random.rand(4,4)*10)
print(p1)
print(p2)
(p1+p2)/2

[[10.  9.  1.  4.]
 [ 0.  5.  9.  1.]
 [ 5.  0.  8.  7.]
 [10.  0.  6.  3.]]
[[9. 8. 3. 5.]
 [8. 8. 1. 4.]
 [7. 9. 4. 1.]
 [3. 9. 6. 4.]]


array([[9.5, 8.5, 2. , 4.5],
       [4. , 6.5, 5. , 2.5],
       [6. , 4.5, 6. , 4. ],
       [6.5, 4.5, 6. , 3.5]])

In [568]:
# How to compute numerical negative value for all elements in a given NumPy array?
p1 = p1 * -1
p1

array([[-10.,  -9.,  -1.,  -4.],
       [ -0.,  -5.,  -9.,  -1.],
       [ -5.,  -0.,  -8.,  -7.],
       [-10.,  -0.,  -6.,  -3.]])

In [580]:
# How to get the floor, ceiling and truncated values of the elements of a numpy array?
d1 = np.random.rand(4,5)*10
print(d1)
print(np.floor(d1))
print(np.ceil(d1))
print(np.trunc(d1))

[[7.75141681 6.1281323  4.93104476 8.6641531  2.20740009]
 [3.91354649 2.03358636 5.57685071 9.51651284 8.37365971]
 [6.14574642 7.15004051 9.66790004 3.70943404 0.47279517]
 [7.56898919 9.74214137 8.63548024 3.13336195 3.18792348]]
[[7. 6. 4. 8. 2.]
 [3. 2. 5. 9. 8.]
 [6. 7. 9. 3. 0.]
 [7. 9. 8. 3. 3.]]
[[ 8.  7.  5.  9.  3.]
 [ 4.  3.  6. 10.  9.]
 [ 7.  8. 10.  4.  1.]
 [ 8. 10.  9.  4.  4.]]
[[7. 6. 4. 8. 2.]
 [3. 2. 5. 9. 8.]
 [6. 7. 9. 3. 0.]
 [7. 9. 8. 3. 3.]]


In [582]:
# How to round elements of the NumPy array to the nearest integer? or Find the round off the values of the given matrix
print(np.round(d1))

[[ 8.  6.  5.  9.  2.]
 [ 4.  2.  6. 10.  8.]
 [ 6.  7. 10.  4.  0.]
 [ 8. 10.  9.  3.  3.]]


In [586]:
# Determine the positive square-root of an array
d1 = np.round(d1) ** 2
print(d1)

[[ 4096.  1296.   625.  6561.    16.]
 [  256.    16.  1296. 10000.  4096.]
 [ 1296.  2401. 10000.   256.     0.]
 [ 4096. 10000.  6561.    81.    81.]]


In [596]:
# Evaluate Einstein’s summation convention of two multidimensional NumPy arrays
d2 = np.round(np.random.rand(10)*10)
print(d2)
np.einsum('i->', d2)

[ 1.  6. 10.  2.  5.  6.  1. 10.  1.  8.]


50.0

In [603]:
# Compute the median of the flattened NumPy array
d1 = np.round(np.random.rand(4,5)*10)
print(d1)
d2 = d1.flatten()
print(d2)
np.median(d2)

[[1. 9. 5. 7. 4.]
 [3. 7. 7. 7. 6.]
 [6. 4. 7. 4. 6.]
 [5. 9. 7. 3. 3.]]
[1. 9. 5. 7. 4. 3. 7. 7. 7. 6. 6. 4. 7. 4. 6. 5. 9. 7. 3. 3.]


6.0

In [605]:
# Find Mean of a List of Numpy Array
np.mean(d2)

5.5

In [607]:
# Calculate the mean of array ignoring the NaN value
d2[4] = np.NaN
d2[7] = np.NaN
print(d2)
np.mean(d2!=np.NaN)

[ 1.  9.  5.  7. nan  3.  7. nan  7.  6.  6.  4.  7.  4.  6.  5.  9.  7.
  3.  3.]


1.0

In [613]:
# Get the mean value from given matrix
matrix_arr = np.matrix(np.round(np.random.rand(6)*10))
print(matrix_arr)

[[ 8.  6.  3.  1.  4. 10.]]


In [615]:
np.matrix.mean(matrix_arr)

5.333333333333333

In [617]:
# Compute the variance of the NumPy array
np.matrix.var(matrix_arr)

9.222222222222221

In [621]:
# Compute the standard deviation of the NumPy array
np.matrix.std(matrix_arr)

3.0368111930480994

In [627]:
# Repeat all the elements of a NumPy array of strings
str_arr = np.array([["Deep", "Hello", "World", "Python", "AI"],
                    ["Deep", "Hello", "World", "Python", "AI"],
                    ["Deep", "Hello", "World", "Python", "AI"],
                    ["Deep", "Hello", "World", "Python", "AI"]], dtype=np.string_)
print(str_arr)
new_strarr = np.char.multiply(str_arr,2)
print(new_strarr)

[[b'Deep' b'Hello' b'World' b'Python' b'AI']
 [b'Deep' b'Hello' b'World' b'Python' b'AI']
 [b'Deep' b'Hello' b'World' b'Python' b'AI']
 [b'Deep' b'Hello' b'World' b'Python' b'AI']]
[[b'DeepDeep' b'HelloHello' b'WorldWorld' b'PythonPython' b'AIAI']
 [b'DeepDeep' b'HelloHello' b'WorldWorld' b'PythonPython' b'AIAI']
 [b'DeepDeep' b'HelloHello' b'WorldWorld' b'PythonPython' b'AIAI']
 [b'DeepDeep' b'HelloHello' b'WorldWorld' b'PythonPython' b'AIAI']]


In [657]:
# How to split the element of a given NumPy array with spaces?
v = np.array([["Here is the thing","We don't talk about it"],["It's all giiberish","I mean it"]],dtype = np.string_)
v

array([[b'Here is the thing', b"We don't talk about it"],
       [b"It's all giiberish", b'I mean it']], dtype='|S22')

In [659]:
np.char.split(v)

array([[list([b'Here', b'is', b'the', b'thing']),
        list([b'We', b"don't", b'talk', b'about', b'it'])],
       [list([b"It's", b'all', b'giiberish']),
        list([b'I', b'mean', b'it'])]], dtype=object)

In [671]:
# How to insert a space between characters of all the elements of a given NumPy array?
# Create a NumPy array of strings
v1 = np.array([["Deep", "Hello", "World", "Python", "AI"],
                    ["Deep", "Hello", "World", "Python", "AI"],
                    ["Deep", "Hello", "World", "Python", "AI"],
                    ["Deep", "Hello", "World", "Python", "AI"]], dtype=np.str_)

# # Insert a space between each character of every element
spaced_v1 = np.char.join(" ", v1)

# Print result
print(spaced_v1)

[['D e e p' 'H e l l o' 'W o r l d' 'P y t h o n' 'A I']
 ['D e e p' 'H e l l o' 'W o r l d' 'P y t h o n' 'A I']
 ['D e e p' 'H e l l o' 'W o r l d' 'P y t h o n' 'A I']
 ['D e e p' 'H e l l o' 'W o r l d' 'P y t h o n' 'A I']]


In [673]:
# Find the length of each string element in the Numpy array
n1 = np.char.str_len(v1)

In [675]:
n1

array([[4, 5, 5, 6, 2],
       [4, 5, 5, 6, 2],
       [4, 5, 5, 6, 2],
       [4, 5, 5, 6, 2]])

In [677]:
np.char.str_len(v)

array([[17, 22],
       [18,  9]])

In [679]:
# Swap the case of an array of stringSwap the case of an array of string
np.char.swapcase(v1)

array([['dEEP', 'hELLO', 'wORLD', 'pYTHON', 'ai'],
       ['dEEP', 'hELLO', 'wORLD', 'pYTHON', 'ai'],
       ['dEEP', 'hELLO', 'wORLD', 'pYTHON', 'ai'],
       ['dEEP', 'hELLO', 'wORLD', 'pYTHON', 'ai']], dtype='<U6')

In [681]:
# Change the case to uppercase of elements of an array
np.char.upper(v1)

array([['DEEP', 'HELLO', 'WORLD', 'PYTHON', 'AI'],
       ['DEEP', 'HELLO', 'WORLD', 'PYTHON', 'AI'],
       ['DEEP', 'HELLO', 'WORLD', 'PYTHON', 'AI'],
       ['DEEP', 'HELLO', 'WORLD', 'PYTHON', 'AI']], dtype='<U6')

In [683]:
# Change the case to lowercase of elements of an array
np.char.lower(v1)

array([['deep', 'hello', 'world', 'python', 'ai'],
       ['deep', 'hello', 'world', 'python', 'ai'],
       ['deep', 'hello', 'world', 'python', 'ai'],
       ['deep', 'hello', 'world', 'python', 'ai']], dtype='<U6')

In [687]:
# Join String by a separator
np.char.join("||",v1)

array([['D||e||e||p', 'H||e||l||l||o', 'W||o||r||l||d',
        'P||y||t||h||o||n', 'A||I'],
       ['D||e||e||p', 'H||e||l||l||o', 'W||o||r||l||d',
        'P||y||t||h||o||n', 'A||I'],
       ['D||e||e||p', 'H||e||l||l||o', 'W||o||r||l||d',
        'P||y||t||h||o||n', 'A||I'],
       ['D||e||e||p', 'H||e||l||l||o', 'W||o||r||l||d',
        'P||y||t||h||o||n', 'A||I']], dtype='<U16')

In [701]:
# Check if two same shaped string arrays one by one
v.shape==v1.shape

False

In [705]:
# Count the number of substrings in an array
v = np.array([["Here is the thing","We don't talk about it"],["It's all giiberish","I mean it"]],dtype = np.str_)
np.char.count(v," ") + 1

array([[4, 5],
       [3, 3]])

In [717]:
# Find the lowest index of the substring in an array
sbstr = "the"
np.char.find(v,sbstr)

array([[ 8, -1],
       [-1, -1]])

In [725]:
# Get the boolean array when values end with a particular character
np.char.endswith(v,"t")

array([[False,  True],
       [False,  True]])