In [1]:
import numpy as np
# Boolean and conditional operator

In [5]:
a = np.array([1,2,3,4])

In [7]:
b = np.array([4,3,2,1])

In [9]:
a<b

array([ True,  True, False, False])

In [11]:
np.all(a<b)

False

In [13]:
np.any(a<b)

True

In [15]:
if np.all(a<b):
    print("All the elements in 'a' are smalller than their corresponding element in 'b'")
elif np.any(a<b):
    print("Some elements in 'a' are smaller than their corresponding elements in b")
else:
    print("Nothing is going as expected")

Some elements in 'a' are smaller than their corresponding elements in b


In [17]:
x = np.array([-2,-1,0,1,2])

In [19]:
x>0

array([False, False, False,  True,  True])

In [21]:
1*(x>0)

array([0, 0, 0, 1, 1])

In [23]:
x*(x>0)

array([0, 0, 0, 1, 2])

In [53]:
def pulse(x,position,height,width):
    # return height * (x>=position) * (x<=(position+width))
    # return height * (x>=position and x<=(position+width)) error because vectorized data on scalar formula
    return height * np.logical_and(x>=position,x<=(position+width))

In [55]:
x = np.linspace(-5,5,11)

In [57]:
x

array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.])

In [59]:
pulse(x,position=-2,height=1,width=5)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0])

In [61]:
pulse(x,position=1,height=1,width=5)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [67]:
x = np.linspace(-5,5,11)

In [69]:
x

array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.])

In [75]:
np.where(x>0,x**2,x**3) #condition, true statement, false statement

array([-125.,  -64.,  -27.,   -8.,   -1.,    0.,    1.,    4.,    9.,
         16.,   25.])

In [77]:
np.select([x<-1,x>2,x>=2],[x**2,x**3,x**4])

array([ 25.,  16.,   9.,   4.,   0.,   0.,   0.,  16.,  27.,  64., 125.])

In [81]:
np.choose([0,0,0,0,1,1,1,2,2,2,2],[x**2,x**3,x**4])

array([ 25.,  16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256., 625.])

In [83]:
np.nonzero(abs(x)>2)

(array([ 0,  1,  2,  8,  9, 10]),)

In [93]:
x[np.nonzero(abs(x)>2)]

array([-5., -4., -3.,  3.,  4.,  5.])

In [95]:
x[abs(x)>2]

array([-5., -4., -3.,  3.,  4.,  5.])