In [1]:
import numpy as np
# Determinants calculation

In [117]:
n = int(input("Enter the order of matrices: "))

Enter the order of matrices:  3


In [119]:
A = np.arange(1,n*n + 1).reshape(n,n)

In [121]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [135]:
def calculate_Determinant(A):
    s = A.shape
    if s == (2,2):
        return A[0][0]*A[1][1] - A[0][1]*A[1][0]
    else:
        d = 0
        for j in range(s[1]):
            d += ((-1)**(j))*A[0][j]*calculate_Determinant(np.delete(np.delete(A,0,axis=0),j,axis=1))
        return d

In [137]:
calculate_Determinant(A)

0

In [139]:
B = np.array([[21,17,7,10],[24,22,6,10],[6,8,2,3],[6,7,1,2]])

In [141]:
B

array([[21, 17,  7, 10],
       [24, 22,  6, 10],
       [ 6,  8,  2,  3],
       [ 6,  7,  1,  2]])

In [143]:
calculate_Determinant(B)

-24

In [145]:
C = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])

In [147]:
C

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [149]:
calculate_Determinant(C)

0