In [1]:
import numpy as np
# fancy indexing

In [3]:
A = np.linspace(0,1,11)

In [5]:
A

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [11]:
A[np.array([0,2,4])]

array([0. , 0.2, 0.4])

In [13]:
A[[0,2,4]]

array([0. , 0.2, 0.4])

In [21]:
f = lambda m,n: n+5*m
A1 = np.fromfunction(f,(7,7),dtype=int)
print(A1)

[[ 0  1  2  3  4  5  6]
 [ 5  6  7  8  9 10 11]
 [10 11 12 13 14 15 16]
 [15 16 17 18 19 20 21]
 [20 21 22 23 24 25 26]
 [25 26 27 28 29 30 31]
 [30 31 32 33 34 35 36]]


In [23]:
A1[[2,3,5],[1,4,5]]

array([11, 19, 30])

In [25]:
# Boolean based indexing

In [27]:
A>0.5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [33]:
A%2==0

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [35]:
A[A>0.5]

array([0.6, 0.7, 0.8, 0.9, 1. ])

In [37]:
# Arrays created using fancy indexing and boolean indexing are not views but independent arrays

In [39]:
A = np.arange(10)

In [41]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
indices = [2,5,7]

In [45]:
B = A[indices]

In [47]:
B

array([2, 5, 7])

In [49]:
B[0] = -1

In [51]:
B

array([-1,  5,  7])

In [53]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
C = A[A%3==0]

In [57]:
C

array([0, 3, 6, 9])

In [59]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
C[0] = 12

In [63]:
C

array([12,  3,  6,  9])

In [65]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
A[A>5] = -1

In [69]:
A

array([ 0,  1,  2,  3,  4,  5, -1, -1, -1, -1])