In [1]:
import numpy as np
# Set Operations

In [4]:
# Test for existance of an arraty of elements in another array

In [6]:
a = np.unique([1,2,3,3]) # unique create a new array with unique elements
b = np.unique([2,3,4,4,5,6,5])

In [8]:
np.in1d(a,b)

array([False,  True,  True])

In [10]:
np.all(np.in1d(a,b))

False

In [12]:
np.union1d(a,b)

array([1, 2, 3, 4, 5, 6])

In [14]:
np.intersect1d(a,b)

array([2, 3])

In [16]:
np.setdiff1d(a,b)

array([1])

In [18]:
np.setdiff1d(b,a)

array([4, 5, 6])